### ISSUE TITLE
165150200111017_SAIFUL WARDI LUBIS_LATIHAN_BAB1

### ISSUE THREAD

**Issue by wardilubis** [advprog-practicuum-if-i-1617/latihan-bab1#8]

**Comment by WardiLubis** [comment]
![Uploading Animated tugas pacman SAIFUL WARDI.gif…]()

**Comment by 99ridho** [comment]
@WardiLubis : source code kamu push ke repositorymu, jangan di issue comment.
**segera perbaiki.**
